#include "archive.h"
#include "filesession.h"
#include "locator.h"
#include "resource.h"
#if defined(USE_REAL)
  #include "include/real/rarchive.h"
#endif //USE_REAL
#if defined(USE_SQLITE)
  #include "include/sqlite/sarchive.h"
#endif //USE_SQLITE
#if defined(USE_ZLIB)
  #include "include/tarc/tcarchive.h"
#endif //USE_ZLIB
#if defined(USE_TAR)
  #include "include/tar/tarchive.h"
#endif //USE_ZLIB